"id" = "estados-br-v1"
"label" = "Estados Brasileiros"
"author" = "Leonardo Piccioni de Almeida"
"baseurl" = "https://upload.wikimedia.org/wikipedia/commons/"

[players]
"Acre" = "./4/4c/Bandeira_do_Acre.svg"
"Alagoas" = "./8/88/Bandeira_de_Alagoas.svg"
"Amapá" = "./0/0c/Bandeira_do_Amap%C3%A1.svg"
"Amazonas" = "./6/6b/Bandeira_do_Amazonas.svg"
"Bahia" = "./2/28/Bandeira_da_Bahia.svg"
"Ceará" = "./2/2e/Bandeira_do_Cear%C3%A1.svg"
"Distrito Federal" = "./3/3c/Bandeira_do_Distrito_Federal_%28Brasil%29.svg"
"Espírito Santo" = "./4/43/Bandeira_do_Esp%C3%ADrito_Santo.svg"
"Goiás" = "./b/be/Flag_of_Goi%C3%A1s.svg"
"Maranhão" = "./4/45/Bandeira_do_Maranh%C3%A3o.svg"
"Mato Grosso" = "./0/0b/Bandeira_de_Mato_Grosso.svg"
"Mato Grosso do Sul" = "./6/64/Bandeira_de_Mato_Grosso_do_Sul.svg"
"Minas Gerais" = "./f/f4/Bandeira_de_Minas_Gerais.svg"
"Pará" = "./0/02/Bandeira_do_Par%C3%A1.svg"
"Paraíba" = "./b/bb/Bandeira_da_Para%C3%ADba.svg"
"Paraná" = "./9/93/Bandeira_do_Paran%C3%A1.svg"
"Pernambuco" = "./5/59/Bandeira_de_Pernambuco.svg"
"Piauí" = "./3/33/Bandeira_do_Piau%C3%AD.svg"
"Rio de Janeiro" = "./7/73/Bandeira_do_estado_do_Rio_de_Janeiro.svg"
"Rio Grande do Norte" = "./3/30/Bandeira_do_Rio_Grande_do_Norte.svg"
"Rio Grande do Sul" = "./6/63/Bandeira_do_Rio_Grande_do_Sul.svg"
"Rondônia" = "./f/fa/Bandeira_de_Rond%C3%B4nia.svg"
"Roraima" = "./9/98/Bandeira_de_Roraima.svg"
"Santa Catarina" = "./1/1a/Bandeira_de_Santa_Catarina.svg"
"São Paulo" = "./2/2b/Bandeira_do_estado_de_S%C3%A3o_Paulo.svg"
"Sergipe" = "./b/be/Bandeira_de_Sergipe.svg"
"Tocantins" = "./f/ff/Bandeira_do_Tocantins.svg"
